# Generated by Django 4.0.3 on 2022-04-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='topic_name',
        ),
        migrations.DeleteModel(
            name='Access_Records',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='webpage',
        ),
    ]
